#!/bin/bash

#SBATCH --nodes=1 
#SBATCH --ntasks-per-node=16
#SBATCH --partition=small_s
#SBATCH --job-name=test
##SBATCH --mem=4G

module load intel/2021.1
module load anaconda/2022.5
source activate leiden

python aimd_run.py
# python run.py
